const PAISES = [
    // ===== AMÉRICA DO SUL =====
    { pais: "Argentina", capital: "Buenos Aires", continente: "América do Sul" },
    { pais: "Bolívia", capital: "La Paz", continente: "América do Sul" },
    { pais: "Brasil", capital: "Brasília", continente: "América do Sul" },
    { pais: "Chile", capital: "Santiago do Chile", continente: "América do Sul" },
    { pais: "Colômbia", capital: "Bogotá", continente: "América do Sul" },
    { pais: "Equador", capital: "Quito", continente: "América do Sul" },
    { pais: "Guiana", capital: "Georgetown", continente: "América do Sul" },
    { pais: "Paraguai", capital: "Assunção", continente: "América do Sul" },
    { pais: "Peru", capital: "Lima", continente: "América do Sul" },
    { pais: "Suriname", capital: "Paramaribo", continente: "América do Sul" },
    { pais: "Uruguai", capital: "Montevideu", continente: "América do Sul" },
    { pais: "Venezuela", capital: "Caracas", continente: "América do Sul" },

    // ===== AMÉRICA DO NORTE E CENTRAL =====
    { pais: "Bahamas", capital: "Nassau", continente: "América do Norte" },
    { pais: "Barbados", capital: "Bridgetown", continente: "América do Norte" },
    { pais: "Belize", capital: "Belmopan", continente: "América do Norte" },
    { pais: "Canadá", capital: "Ottawa", continente: "América do Norte" },
    { pais: "Costa Rica", capital: "São José", continente: "América do Norte" },
    { pais: "Cuba", capital: "Havana", continente: "América do Norte" },
    { pais: "Dominica", capital: "Roseau", continente: "América do Norte" },
    { pais: "El Salvador", capital: "San Salvador", continente: "América do Norte" },
    { pais: "Estados Unidos", capital: "Washington", continente: "América do Norte" },
    { pais: "Guatemala", capital: "Cidade da Guatemala", continente: "América do Norte" },
    { pais: "Haiti", capital: "Porto Príncipe", continente: "América do Norte" },
    { pais: "Honduras", capital: "Tegucigalpa", continente: "América do Norte" },
    { pais: "Jamaica", capital: "Kingston", continente: "América do Norte" },
    { pais: "México", capital: "Cidade do México", continente: "América do Norte" },
    { pais: "Nicarágua", capital: "Manágua", continente: "América do Norte" },
    { pais: "Panamá", capital: "Cidade do Panamá", continente: "América do Norte" },
    { pais: "República Dominicana", capital: "Santo Domingo", continente: "América do Norte" },
    { pais: "Santa Lúcia", capital: "Castries", continente: "América do Norte" },
    { pais: "São Cristóvão e Neves", capital: "Basseterre", continente: "América do Norte" },
    { pais: "São Vicente e Granadinas", capital: "Kingstown", continente: "América do Norte" },
    { pais: "Trindade e Tobago", capital: "Porto de Espanha", continente: "América do Norte" },

    // ===== EUROPA =====
    { pais: "Albânia", capital: "Tirana", continente: "Europa" },
    { pais: "Alemanha", capital: "Berlim", continente: "Europa" },
    { pais: "Andorra", capital: "Andorra-a-Velha", continente: "Europa" },
    { pais: "Áustria", capital: "Viena", continente: "Europa" },
    { pais: "Bélgica", capital: "Bruxelas", continente: "Europa" },
    { pais: "Bielorrússia", capital: "Minsk", continente: "Europa" },
    { pais: "Bósnia e Herzegovina", capital: "Sarajevo", continente: "Europa" },
    { pais: "Bulgária", capital: "Sófia", continente: "Europa" },
    { pais: "Croácia", capital: "Zagreb", continente: "Europa" },
    { pais: "Dinamarca", capital: "Copenhaga", continente: "Europa" },
    { pais: "Eslováquia", capital: "Bratislava", continente: "Europa" },
    { pais: "Eslovénia", capital: "Liubliana", continente: "Europa" },
    { pais: "Espanha", capital: "Madrid", continente: "Europa" },
    { pais: "Estónia", capital: "Tallinn", continente: "Europa" },
    { pais: "Finlândia", capital: "Helsínquia", continente: "Europa" },
    { pais: "França", capital: "Paris", continente: "Europa" },
    { pais: "Grécia", capital: "Atenas", continente: "Europa" },
    { pais: "Hungria", capital: "Budapeste", continente: "Europa" },
    { pais: "Irlanda", capital: "Dublin", continente: "Europa" },
    { pais: "Islândia", capital: "Reiquiavique", continente: "Europa" },
    { pais: "Itália", capital: "Roma", continente: "Europa" },
    { pais: "Letónia", capital: "Riga", continente: "Europa" },
    { pais: "Liechtenstein", capital: "Vaduz", continente: "Europa" },
    { pais: "Lituânia", capital: "Vilnius", continente: "Europa" },
    { pais: "Luxemburgo", capital: "Luxemburgo", continente: "Europa" },
    { pais: "Macedónia do Norte", capital: "Escópia", continente: "Europa" },
    { pais: "Malta", capital: "Valeta", continente: "Europa" },
    { pais: "Moldávia", capital: "Chisinau", continente: "Europa" },
    { pais: "Mónaco", capital: "Mónaco", continente: "Europa" },
    { pais: "Montenegro", capital: "Podgorica", continente: "Europa" },
    { pais: "Noruega", capital: "Oslo", continente: "Europa" },
    { pais: "Polónia", capital: "Varsóvia", continente: "Europa" },
    { pais: "Portugal", capital: "Lisboa", continente: "Europa" },
    { pais: "Reino Unido", capital: "Londres", continente: "Europa" },
    { pais: "República Checa", capital: "Praga", continente: "Europa" },
    { pais: "Roménia", capital: "Bucareste", continente: "Europa" },
    { pais: "San Marino", capital: "San Marino", continente: "Europa" },
    { pais: "Sérvia", capital: "Belgrado", continente: "Europa" },
    { pais: "Suécia", capital: "Estocolmo", continente: "Europa" },
    { pais: "Suíça", capital: "Berna", continente: "Europa" },
    { pais: "Ucrânia", capital: "Kiev", continente: "Europa" },

    // ===== ÁSIA =====
    { pais: "Afeganistão", capital: "Cabul", continente: "Ásia" },
    { pais: "Arábia Saudita", capital: "Riade", continente: "Ásia" },
    { pais: "Arménia", capital: "Erevão", continente: "Ásia" },
    { pais: "Azerbaijão", capital: "Baku", continente: "Ásia" },
    { pais: "Bahrein", capital: "Manama", continente: "Ásia" },
    { pais: "Bangladesh", capital: "Daca", continente: "Ásia" },
    { pais: "Brunei", capital: "Bandar Seri Begawan", continente: "Ásia" },
    { pais: "Butão", capital: "Thimbu", continente: "Ásia" },
    { pais: "Camboja", capital: "Phnom Penh", continente: "Ásia" },
    { pais: "Catar", capital: "Doha", continente: "Ásia" },
    { pais: "Cazaquistão", capital: "Astana", continente: "Ásia" },
    { pais: "China", capital: "Pequim", continente: "Ásia" },
    { pais: "Chipre", capital: "Nicósia", continente: "Ásia" },
    { pais: "Coreia do Norte", capital: "Pyongyang", continente: "Ásia" },
    { pais: "Coreia do Sul", capital: "Seul", continente: "Ásia" },
    { pais: "Emirados Árabes Unidos", capital: "Abu Dhabi", continente: "Ásia" },
    { pais: "Filipinas", capital: "Manila", continente: "Ásia" },
    { pais: "Geórgia", capital: "Tbilisi", continente: "Ásia" },
    { pais: "Iémen", capital: "Saná", continente: "Ásia" },
    { pais: "Índia", capital: "Nova Deli", continente: "Ásia" },
    { pais: "Indonésia", capital: "Jacarta", continente: "Ásia" },
    { pais: "Irão", capital: "Teerão", continente: "Ásia" },
    { pais: "Iraque", capital: "Bagdade", continente: "Ásia" },
    { pais: "Japão", capital: "Tóquio", continente: "Ásia" },
    { pais: "Jordânia", capital: "Amã", continente: "Ásia" },
    { pais: "Kuwait", capital: "Kuwait", continente: "Ásia" },
    { pais: "Laos", capital: "Vientiane", continente: "Ásia" },
    { pais: "Líbano", capital: "Beirute", continente: "Ásia" },
    { pais: "Malásia", capital: "Kuala Lumpur", continente: "Ásia" },
    { pais: "Maldivas", capital: "Malé", continente: "Ásia" },
    { pais: "Mongólia", capital: "Ulaanbaatar", continente: "Ásia" },
    { pais: "Myanmar", capital: "Nay Pyi Taw", continente: "Ásia" },
    { pais: "Nepal", capital: "Catmandu", continente: "Ásia" },
    { pais: "Omã", capital: "Mascate", continente: "Ásia" },
    { pais: "Paquistão", capital: "Islamabad", continente: "Ásia" },
    { pais: "Quirguistão", capital: "Bishkek", continente: "Ásia" },
    { pais: "Rússia", capital: "Moscovo", continente: "Europa/Ásia" },
    { pais: "Singapura", capital: "Singapura", continente: "Ásia" },
    { pais: "Síria", capital: "Damasco", continente: "Ásia" },
    { pais: "Sri Lanka", capital: "Sri Jayawardenapura Kotte", continente: "Ásia" },
    { pais: "Tailândia", capital: "Banguecoque", continente: "Ásia" },
    { pais: "Tajiquistão", capital: "Duchambe", continente: "Ásia" },
    { pais: "Timor-Leste", capital: "Díli", continente: "Ásia" },
    { pais: "Turquemenistão", capital: "Asgabate", continente: "Ásia" },
    { pais: "Turquia", capital: "Ancara", continente: "Ásia" },
    { pais: "Uzbequistão", capital: "Tasquente", continente: "Ásia" },
    { pais: "Vietname", capital: "Hanói", continente: "Ásia" },

    // ===== ÁFRICA =====
    { pais: "África do Sul", capital: "Pretória", continente: "África" },
    { pais: "Angola", capital: "Luanda", continente: "África" },
    { pais: "Argélia", capital: "Argel", continente: "África" },
    { pais: "Benim", capital: "Porto-Novo", continente: "África" },
    { pais: "Botsuana", capital: "Gaborone", continente: "África" },
    { pais: "Burkina Faso", capital: "Ouagadougou", continente: "África" },
    { pais: "Burundi", capital: "Gitega", continente: "África" },
    { pais: "Cabo Verde", capital: "Praia", continente: "África" },
    { pais: "Camarões", capital: "Yaoundé", continente: "África" },
    { pais: "Chade", capital: "Jamena", continente: "África" },
    { pais: "Comores", capital: "Moroni", continente: "África" },
    { pais: "Congo (República)", capital: "Brazzaville", continente: "África" },
    { pais: "Congo (RDC)", capital: "Kinshasa", continente: "África" },
    { pais: "Costa do Marfim", capital: "Yamoussoukro", continente: "África" },
    { pais: "Djibouti", capital: "Djibouti", continente: "África" },
    { pais: "Egito", capital: "Cairo", continente: "África" },
    { pais: "Eritreia", capital: "Asmara", continente: "África" },
    { pais: "Essuatíni", capital: "Mbabane", continente: "África" },
    { pais: "Etiópia", capital: "Adis Abeba", continente: "África" },
    { pais: "Gabão", capital: "Libreville", continente: "África" },
    { pais: "Gâmbia", capital: "Banjul", continente: "África" },
    { pais: "Gana", capital: "Acra", continente: "África" },
    { pais: "Guiné", capital: "Conacri", continente: "África" },
    { pais: "Guiné Equatorial", capital: "Malabo", continente: "África" },
    { pais: "Guiné-Bissau", capital: "Bissau", continente: "África" },
    { pais: "Lesoto", capital: "Maseru", continente: "África" },
    { pais: "Libéria", capital: "Monróvia", continente: "África" },
    { pais: "Líbia", capital: "Trípoli", continente: "África" },
    { pais: "Madagáscar", capital: "Antananarivo", continente: "África" },
    { pais: "Malawi", capital: "Lilongwe", continente: "África" },
    { pais: "Mali", capital: "Bamako", continente: "África" },
    { pais: "Mauritânia", capital: "Nouakchott", continente: "África" },
    { pais: "Maurícia", capital: "Port Louis", continente: "África" },
    { pais: "Marrocos", capital: "Rabat", continente: "África" },
    { pais: "Moçambique", capital: "Maputo", continente: "África" },
    { pais: "Namíbia", capital: "Windhoek", continente: "África" },
    { pais: "Níger", capital: "Niamey", continente: "África" },
    { pais: "Nigéria", capital: "Abuja", continente: "África" },
    { pais: "Quénia", capital: "Nairobi", continente: "África" },
    { pais: "República Centro-Africana", capital: "Bangui", continente: "África" },
    { pais: "Ruanda", capital: "Kigali", continente: "África" },
    { pais: "São Tomé e Príncipe", capital: "São Tomé", continente: "África" },
    { pais: "Senegal", capital: "Dacar", continente: "África" },
    { pais: "Serra Leoa", capital: "Freetown", continente: "África" },
    { pais: "Seicheles", capital: "Vitória", continente: "África" },
    { pais: "Somália", capital: "Mogadíscio", continente: "África" },
    { pais: "Sudão", capital: "Cartum", continente: "África" },
    { pais: "Sudão do Sul", capital: "Juba", continente: "África" },
    { pais: "Tanzânia", capital: "Dodoma", continente: "África" },
    { pais: "Togo", capital: "Lomé", continente: "África" },
    { pais: "Tunísia", capital: "Tunes", continente: "África" },
    { pais: "Uganda", capital: "Campala", continente: "África" },
    { pais: "Zâmbia", capital: "Lusaca", continente: "África" },
    { pais: "Zimbabué", capital: "Harare", continente: "África" },

    // ===== OCEANIA =====
    { pais: "Austrália", capital: "Camberra", continente: "Oceania" },
    { pais: "Fiji", capital: "Suva", continente: "Oceania" },
    { pais: "Ilhas Marshall", capital: "Majuro", continente: "Oceania" },
    { pais: "Kiribati", capital: "Tarawa", continente: "Oceania" },
    { pais: "Micronésia", capital: "Palikir", continente: "Oceania" },
    { pais: "Nauru", capital: "Yaren", continente: "Oceania" },
    { pais: "Nova Zelândia", capital: "Wellington", continente: "Oceania" },
    { pais: "Palau", capital: "Ngerulmud", continente: "Oceania" },
    { pais: "Papua-Nova Guiné", capital: "Port Moresby", continente: "Oceania" },
    { pais: "Samoa", capital: "Apia", continente: "Oceania" },
    { pais: "Salomão", capital: "Honiara", continente: "Oceania" },
    { pais: "Tuvalu", capital: "Funafuti", continente: "Oceania" },
    { pais: "Vanuatu", capital: "Port Vila", continente: "Oceania" }
];